name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node env
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Run nextjs lint
        run: npm run next:lint --max-warnings=0

      - name: Check typings on nextjs
        run: npm run next:check-types

      - name: Run tests
        run: npm run test

      - name: Build nextjs
        run: npm run next:build
